name: SSE CI/CD
on: [push]
jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install cmake"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: "Install black"
        run: pip install black
      - name: "Check style with black"
        run: black --check .
  